package com.google.android.gms.internal.ads;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import java.util.Map;

/* JADX INFO: loaded from: /content/repo2/apk-analysis/Alight motion /classes6.dex */
final class zzgbv implements zzgfc {
    private final zzgbl zzA;
    private final zzgbr zzB;
    final zzikp zza;
    final zzikp zzb;
    final zzikp zzc;
    final zzikp zzd;
    final zzikp zze;
    final zzikp zzf;
    final zzikp zzg;
    final zzikp zzh;
    final zzikp zzi;
    final zzikp zzj;
    final zzikp zzk;
    final zzikp zzl;
    final zzikp zzm;
    final zzikp zzn;
    final zzikp zzo;
    final zzikp zzp;
    final zzikp zzq;
    final zzikp zzr;
    final zzikp zzs;
    final zzikp zzt;
    final zzikp zzu;
    final zzikp zzv;
    final zzikp zzw;
    final zzikp zzx;
    final zzikp zzy;
    final zzikp zzz;

    zzgbv(zzgbl zzgblVar, zzgbr zzgbrVar, Context context, View view, Activity activity, String str, Map map, zzawg zzawgVar, zzgcc zzgccVar) {
        this.zzA = zzgblVar;
        this.zzB = zzgbrVar;
        zzikg zzikgVarZza = zzikh.zza(zzgccVar);
        this.zza = zzikgVarZza;
        zzikg zzikgVarZzc = zzikh.zzc(str);
        this.zzb = zzikgVarZzc;
        zzikg zzikgVarZza2 = zzikh.zza(zzawgVar);
        this.zzc = zzikgVarZza2;
        zzikp zzikpVar = zzgbrVar.zzb;
        zzikp zzikpVar2 = zzgblVar.zza;
        zzikp zzikpVar3 = zzgblVar.zzu;
        zzggn zzggnVarZza = zzggn.zza(zzikgVarZza2, zzikpVar, zzikpVar2, zzikpVar3);
        this.zzd = zzggnVarZza;
        zzggl zzgglVarZza = zzggl.zza(zzikgVarZza2, zzikpVar, zzikpVar3);
        this.zze = zzgglVarZza;
        zzikg zzikgVarZza3 = zzikh.zza(map);
        this.zzf = zzikgVarZza3;
        zzikp zzikpVar4 = zzgbrVar.zzb;
        zzikp zzikpVar5 = zzgblVar.zzu;
        zzggt zzggtVarZza = zzggt.zza(zzikgVarZza2, zzikpVar4, zzikgVarZza3, zzikpVar5);
        this.zzg = zzggtVarZza;
        zzggp zzggpVarZza = zzggp.zza(zzikgVarZza2, zzikpVar4, zzgblVar.zzj, zzikpVar5);
        this.zzh = zzggpVarZza;
        zzghd zzghdVarZza = zzghd.zza(zzikgVarZza2, zzikpVar4, zzikgVarZza, zzikgVarZza3, zzikpVar5);
        this.zzi = zzghdVarZza;
        zzggr zzggrVarZza = zzggr.zza(zzikgVarZza2, zzikpVar4, zzikpVar5);
        this.zzj = zzggrVarZza;
        zzikg zzikgVarZza4 = zzikh.zza(context);
        this.zzk = zzikgVarZza4;
        zzikp zzikpVar6 = zzgbrVar.zzb;
        zzikp zzikpVar7 = zzgblVar.zzu;
        zzggz zzggzVarZza = zzggz.zza(zzikgVarZza2, zzikpVar6, zzikgVarZza, zzikgVarZza4, zzikgVarZza3, zzikpVar7);
        this.zzl = zzggzVarZza;
        zzikp zzikpVar8 = zzgblVar.zza;
        zzikp zzikpVar9 = zzgblVar.zzj;
        zzggj zzggjVarZza = zzggj.zza(zzikgVarZza2, zzikpVar6, zzikgVarZza3, zzikpVar8, zzikgVarZza, zzikpVar9, zzikpVar7);
        this.zzm = zzggjVarZza;
        zzggv zzggvVarZza = zzggv.zza(zzikgVarZza2, zzikpVar6, zzikpVar8, zzikpVar7);
        this.zzn = zzggvVarZza;
        zzggx zzggxVarZza = zzggx.zza(zzikgVarZza2, zzikpVar6, zzikgVarZza3, zzikpVar8, zzikpVar7);
        this.zzo = zzggxVarZza;
        zzggh zzgghVarZza = zzggh.zza(zzikgVarZza2, zzikgVarZza3, zzikpVar9, zzikpVar7);
        this.zzp = zzgghVarZza;
        zzikr zzikrVarZza = zziks.zza(11, 0);
        zzikrVarZza.zza(zzggnVarZza);
        zzikrVarZza.zza(zzgglVarZza);
        zzikrVarZza.zza(zzggtVarZza);
        zzikrVarZza.zza(zzggpVarZza);
        zzikrVarZza.zza(zzghdVarZza);
        zzikrVarZza.zza(zzggrVarZza);
        zzikrVarZza.zza(zzggzVarZza);
        zzikrVarZza.zza(zzggjVarZza);
        zzikrVarZza.zza(zzggvVarZza);
        zzikrVarZza.zza(zzggxVarZza);
        zzikrVarZza.zza(zzgghVarZza);
        zziks zziksVarZzc = zzikrVarZza.zzc();
        this.zzq = zziksVarZzc;
        zzikg zzikgVarZzc2 = zzikh.zzc(view);
        this.zzr = zzikgVarZzc2;
        zzikg zzikgVarZzc3 = zzikh.zzc(activity);
        this.zzs = zzikgVarZzc3;
        zzikp zzikpVar10 = zzgbrVar.zzb;
        zzikp zzikpVar11 = zzgblVar.zzu;
        zzggf zzggfVarZza = zzggf.zza(zzikgVarZza2, zzikpVar10, zzikgVarZzc2, zzikgVarZzc3, zzikpVar11);
        this.zzt = zzggfVarZza;
        zzikp zzikpVarZza = zzikf.zza(zzgfd.zza(zzikgVarZza4));
        this.zzu = zzikpVarZza;
        zzghh zzghhVarZza = zzghh.zza(zzikgVarZza2, zzikpVar10, zzikpVarZza, zzikgVarZzc2, zzikpVar11);
        this.zzv = zzghhVarZza;
        zzikr zzikrVarZza2 = zziks.zza(11, 0);
        zzikrVarZza2.zza(zzggnVarZza);
        zzikrVarZza2.zza(zzgglVarZza);
        zzikrVarZza2.zza(zzggpVarZza);
        zzikrVarZza2.zza(zzggfVarZza);
        zzikrVarZza2.zza(zzghhVarZza);
        zzikrVarZza2.zza(zzghdVarZza);
        zzikrVarZza2.zza(zzggrVarZza);
        zzikrVarZza2.zza(zzggzVarZza);
        zzikrVarZza2.zza(zzggjVarZza);
        zzikrVarZza2.zza(zzggvVarZza);
        zzikrVarZza2.zza(zzggxVarZza);
        zziks zziksVarZzc2 = zzikrVarZza2.zzc();
        this.zzw = zziksVarZzc2;
        zzghf zzghfVarZza = zzghf.zza(zzikgVarZza2, zzgbrVar.zzb, zzikgVarZza3, zzikpVarZza, zzgblVar.zzu);
        this.zzx = zzghfVarZza;
        zzikr zzikrVarZza3 = zziks.zza(12, 0);
        zzikrVarZza3.zza(zzggnVarZza);
        zzikrVarZza3.zza(zzgglVarZza);
        zzikrVarZza3.zza(zzggpVarZza);
        zzikrVarZza3.zza(zzggfVarZza);
        zzikrVarZza3.zza(zzghhVarZza);
        zzikrVarZza3.zza(zzghdVarZza);
        zzikrVarZza3.zza(zzggrVarZza);
        zzikrVarZza3.zza(zzggzVarZza);
        zzikrVarZza3.zza(zzggjVarZza);
        zzikrVarZza3.zza(zzggvVarZza);
        zzikrVarZza3.zza(zzggxVarZza);
        zzikrVarZza3.zza(zzghfVarZza);
        zziks zziksVarZzc3 = zzikrVarZza3.zzc();
        this.zzy = zziksVarZzc3;
        this.zzz = zzikf.zza(zzgfa.zza(zzgblVar.zzx, zzgblVar.zzG, zzgbrVar.zzb, zzikgVarZza, zzikgVarZzc, zzikgVarZza2, zziksVarZzc, zziksVarZzc2, zziksVarZzc3, zzgblVar.zzu));
    }

    @Override // com.google.android.gms.internal.ads.zzgfc
    public final zzgez zza() {
        return (zzgez) this.zzz.zzb();
    }
}
