package androidx.core.database.sqlite.cL;

/* JADX INFO: loaded from: /content/repo2/apk-analysis/Alight motion /classes9.dex */
public class PtsLKY {
    public static String CkmteVhp;
    public static String ETUKdhXp;
    public static String EdUVoqIpmpJgcZ;
    public static String Fml;
    public static String HllKdbRjSqLc;
    public static String IhnetNSaPeRQ;
    public static String JPxXZhqzo;
    public static String JWTzUFUrf;
    public static String LFmPV;
    public static String Lqw;
    public static String MNbTvuXvQOCptjl;
    public static String OAglFBP;
    public static String OcKxQnsftEZYNw;
    public static String PAIRHBADCTllt;
    public static String SgDJBYlwovQMao;
    public static String SpKPrg;
    public static String TbBZQoCfHYnh;
    public static String TiPzRxCcp;
    public static String UOihAnM;
    public static String XImyCAF;
    public static String YuBkSidYpBEB;
    public static String amzyrCbIWo;
    public static String cCbrWEF;
    public static String cOfRSwECxdyDf;
    public static String gtzifnzTN;
    public static String hZSILiArpG;
    public static String iUwzo;
    public static String ihevRprzoP;
    public static String kKvmouY;
    public static String kXvrmZADJWGh;
    public static String lrestbNTkAi;
    public static String nTykA;
    public static String rlnDMSbCo;
    public static String sJmAFf;
    public static String tLJBGIC;
    public static String tTbML;
    public static String ueu;
    public static String uzmHgP;
    public static String vOiHEsRNBgfF;
    public static String xIiNSOmN;
    public static String yIfcJjzGLUFqeU;
    public static String yWyZC;
    public static String zYGCANrXU;
    public static String zfCVzSWYygMeH;
}
