package com.fyber.inneractive.sdk.network;

import Msr.Ml;
import com.vungle.ads.internal.protos.Sdk;
import java.util.HashMap;

/* JADX INFO: loaded from: /content/repo2/apk-analysis/Alight motion /classes9.dex */
public enum t {
    VAST_ERROR_DVC_FAILURE(46),
    FMP_SDK_INIT_FAILED(62),
    VAST_COMPANION_FAILED_LOADING(70),
    VAST_COMPANION_INCOMPATIBLE_MIMETYPE(75),
    FMP_COMPANION_FAILED_LOADING(78),
    ERROR_STORE_PROMO_FAILURE(96),
    VAST_ERROR_INVALID_RESPONSE(Sdk.SDKError.Reason.MRAID_ERROR_VALUE),
    VAST_ERROR_TOO_MANY_WRAPPERS(Sdk.SDKError.Reason.INVALID_IFA_STATUS_VALUE),
    VAST_ERROR_NO_MEDIA_FILES(303),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(Sdk.SDKError.Reason.AD_EXPIRED_VALUE),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(306),
    VAST_ERROR_BUFFER_TIMEOUT(307),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(308),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(Sdk.SDKError.Reason.MRAID_JS_CALL_EMPTY_VALUE),
    VAST_ERROR_UNSECURE_URL(Sdk.SDKError.Reason.DEEPLINK_OPEN_FAILED_VALUE),
    MRAID_ERROR_UNSECURE_CONTENT(Sdk.SDKError.Reason.EVALUATE_JAVASCRIPT_FAILED_VALUE),
    VPAID_ERROR_UNSECURE_CONTENT(Sdk.SDKError.Reason.LINK_COMMAND_OPEN_FAILED_VALUE),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(401),
    NATIVE_ERROR_FAILED_TO_LOAD_AD(402),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(404),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(405),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(406),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(407),
    NATIVE_ERROR_FAILED_LOAD_ASSET(410),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(411),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(412),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(413),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(414),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(415),
    MRAID_AUTO_ACTION_DETECTED(501),
    FIRST_PARTY_EXTRA_DATA_ERROR(550),
    INTERNAL_CONFIG_MISMATCH(Sdk.SDKError.Reason.NATIVE_VIDEO_PLAYBACK_ERROR_VALUE),
    FATAL_ADM_PARSING_ERROR(603),
    FATAL_ADM_MARKUP_FETCHING_ERROR(604),
    TOKEN_EXCEEDS_LIMIT(605),
    IGNITE_FLOW_MODE_NOT_COMPATIBLE(606),
    IGNITE_FLOW_FAILED_TO_START(607),
    IGNITE_FLOW_FAILED_TO_INSTALL_APP(612),
    IGNITE_FLOW_FAILED_TO_LOAD_WEBPAGE(613),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(704),
    IA_AD_LOAD_FAILED(801),
    IA_AD_EXPIRED(802),
    IA_AD_DESTROYED_WITHOUT_SHOW(803),
    IA_AD_FAILURE_DATA(850),
    CLICK_PARSING_FAILURE(991),
    MISSMATCH_SPOTID(992),
    FAILED_DNS(995),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001),
    ODT_ENCRYPTION_EXCEPTION(Ml.ENCRYPTION_EXCEPTION.n()),
    ODT_RAW_ONE_DT_ERROR(Ml.RAW_ONE_DT_ERROR.n()),
    ODT_ONE_DT_PARSE_ERROR(Ml.ONE_DT_PARSE_ERROR.n()),
    ODT_ONE_DT_AUTHENTICATION_ERROR(Ml.ONE_DT_AUTHENTICATION_ERROR.n()),
    ODT_ONE_DT_BROADCAST_ERROR(Ml.ONE_DT_BROADCAST_ERROR.n()),
    ODT_ONE_DT_REQUEST_ERROR(Ml.ONE_DT_REQUEST_ERROR.n()),
    ODT_ONE_DT_GENERAL_ERROR(Ml.ONE_DT_GENERAL_ERROR.n());

    private static final HashMap<Integer, t> sMap = new HashMap<>();
    int val;

    static {
        for (t tVar : values()) {
            sMap.put(Integer.valueOf(tVar.val), tVar);
        }
    }

    public static t a(Ml ml) {
        return sMap.get(Integer.valueOf(ml.n()));
    }

    t(int i2) {
        this.val = i2;
    }
}
