package gq;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import pUk.C2331c;

/* JADX INFO: loaded from: /content/repo2/apk-analysis/Alight motion /classes6.dex */
abstract class Wre {
    private static void O(StringBuilder sb) {
        sb.append((char) 1);
        sb.append((char) 1);
    }

    static String J2(String str) {
        StringBuilder sb = new StringBuilder(str);
        int length = sb.length() - 1;
        char cCharAt = sb.charAt(length);
        wqP.n.t(cCharAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb.setCharAt(length, (char) (cCharAt + 1));
        return sb.toString();
    }

    static String t(pUk.I28 i28) {
        StringBuilder sb = new StringBuilder();
        int iTy = i28.ty();
        for (int i2 = 0; i2 < iTy; i2++) {
            if (sb.length() > 0) {
                O(sb);
            }
            nr(i28.mUb(i2), sb);
        }
        O(sb);
        return sb.toString();
    }

    private static List n(String str) {
        boolean z2;
        int length = str.length();
        boolean z3 = false;
        if (length >= 2) {
            z2 = true;
        } else {
            z2 = false;
        }
        wqP.n.t(z2, "Invalid path \"%s\"", str);
        if (length == 2) {
            if (str.charAt(0) == 1 && str.charAt(1) == 1) {
                z3 = true;
            }
            wqP.n.t(z3, "Non-empty path \"%s\" had length 2", str);
            return Collections.EMPTY_LIST;
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb = new StringBuilder();
        int i2 = 0;
        while (i2 < length) {
            int iIndexOf = str.indexOf(1, i2);
            if (iIndexOf >= 0 && iIndexOf <= length2) {
                int i3 = iIndexOf + 1;
                char cCharAt = str.charAt(i3);
                if (cCharAt != 1) {
                    if (cCharAt != 16) {
                        if (cCharAt == 17) {
                            sb.append(str.substring(i2, i3));
                        } else {
                            throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
                        }
                    } else {
                        sb.append(str.substring(i2, iIndexOf));
                        sb.append((char) 0);
                    }
                } else {
                    String strSubstring = str.substring(i2, iIndexOf);
                    if (sb.length() != 0) {
                        sb.append(strSubstring);
                        strSubstring = sb.toString();
                        sb.setLength(0);
                    }
                    arrayList.add(strSubstring);
                }
                i2 = iIndexOf + 2;
            } else {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
        }
        return arrayList;
    }

    private static void nr(String str, StringBuilder sb) {
        int length = str.length();
        for (int i2 = 0; i2 < length; i2++) {
            char cCharAt = str.charAt(i2);
            if (cCharAt != 0) {
                if (cCharAt != 1) {
                    sb.append(cCharAt);
                } else {
                    sb.append((char) 1);
                    sb.append((char) 17);
                }
            } else {
                sb.append((char) 1);
                sb.append((char) 16);
            }
        }
    }

    static C2331c rl(String str) {
        return C2331c.r(n(str));
    }
}
